[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dapp = "GENB5E93yFBPeR9ZCT5NpmV4n9BmmU1BurNoJ2ootYWd"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/superstar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
